-- 코드를 입력하세요
SELECT b.TITLE, b.BOARD_ID, r.REPLY_ID, r.WRITER_ID, r.CONTENTS, 
DATE_FORMAT(r.CREATED_DATE,'%Y-%m-%d') AS CREATED_DATE
FROM USED_GOODS_BOARD b
JOIN USED_GOODS_REPLY r
ON b.BOARD_ID = r.BOARD_ID
WHERE YEAR(b.CREATED_DATE) = 2022 AND MONTH(b.CREATED_DATE) = 10
ORDER BY r.CREATED_DATE ASC, b.TITLE ASC;

-- 무슨 기준으로 ON을 해야 할까? 아 두 개의 테이블을 비교하니까 BOARD_ID만 같네 그러면 이거를 기준으로 해야겠다.
-- 게시글 게시글
-- 댓글 댓글 댓글, 댓글